name: FLClassify
version: "0.1.0"
license: "MIT"
date: 2022-11-10
description: |
    Classify formal languages

authors:
    - name: Dakotah Lambert
      url: https://vvulpes0.github.io/

maintainers:
    - name: Dakotah Lambert
      url: https://vvulpes0.github.io/

GAP: ">= 4.11"

needed-pkgs:
    - name: "semigroups"
      version: ">= 5.0"
      url: "https://semigroups.github.io/Semigroups"
    - name: "automata"
      version: ">= 1.14"
      url: "https://gap-packages.github.io/automata/"

www: https://vvulpes0.github.io/flclassify/
readme: README.md
packageinfo: https://vvulpes0.github.io/flclassify/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/vvulpes0/flclassify/releases/download/v0.1.0/FLClassify-0.1.0.tar.gz

abstract: |

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Lam22</span>]   <b class='BibAuthor'>Lambert, D.</b>,
     <i class='BibTitle'>FLClassify, Classify formal languages,
             Version 0.1.0</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://vvulpes0.github.io/flclassify/">https://vvulpes0.github.io/flclassify/</a></span>.
    </p>
    

bibtex: |
    @misc{ FLClassify0.1.0,
      author =           {Lambert, D.},
      title =            {{FLClassify},  Classify  formal  languages,  {V}ersion
                          0.1.0},
      month =            {Nov},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href         {https://vvulpes0.github.io/flclassify/}
                          {\texttt{https://vvulpes0.github.io/}\discretionary
                          {}{}{}\texttt{flclassify/}}},
      printedkey =       {Lam22}
    }

